In [6]:
import numpy as np

## Задание 1

In [26]:
N = 10
A = np.arange(N-1, -1, -1)

In [28]:
A

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## Задание 2

In [30]:
D = np.diag(A)
D

array([[9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [32]:
np.sum(A)

45

## Задание 3

4x + 2y + z = 4 <p>
x + 3y = 12 <p>
5y + 4z = -3

In [61]:
A = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])
np.linalg.solve(A, b)

array([ 0.46666667,  3.84444444, -5.55555556])

## Задание 4

In [68]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [93]:
def cos(users_stats, next_user_stats):
    cos = 0
    for i, user in enumerate(users_stats):
        cos1 = np.dot(user, next_user_stats) / np.linalg.norm(user) / np.linalg.norm(next_user_stats)
        if cos1 > cos:
            similar_user = i + 1
        cos = cos1
    
    print(f'Самый похожий пользователь - пользователь №{similar_user} (его покупки - {users_stats[similar_user - 1]})')

cos(users_stats, next_user_stats)

Самый похожий пользователь - пользователь №8 (его покупки - [0 1 1 0 0 0])
